[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
verbosity = 5
fuzz_runs = 256    

# See more config options https://github.com/gakonst/foundry/tree/master/config